# ROS node settings
traj_server_rate: 200 # Should be 200 Hz or less for HID comms
data_channel: "pressure_control"
use_traj_server: True

# HID Device Info
# The first controller
devices:
  - vendor_id: 5824
    product_id: 1158
    serial_number: 6467390
    num_channels: 8
    cmd_spec: '2.1'
    cmd_format: '%0.2f'

  # The second controller
  - vendor_id: 5824
    product_id: 1158
    serial_number: 5587550 #4913830
    num_channels: 8
    cmd_spec: '2.1'
    cmd_format: '%0.2f'
