# ROS node settings
traj_server_rate: 20 # Should be < 40 Hz for serial comms
data_channel: "servo"
use_traj_server: True

# Serial device info
devices:
  - devname: /dev/ttyACM0
    baudrate: 2000000 #115200
    num_channels: 8
    cmd_spec: '2.1'
    cmd_format: '%0.2f'